apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: seongjaegreen/templify-gateway
          ports:
            - containerPort: 8080
          env:
            - name: AUTH_SERVICE_URI
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: AUTH_SERVICE_URI
            - name: WRITE_SERVICE_URI
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: WRITE_SERVICE_URI
            - name: HISTORY_SERVICE_URI
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: HISTORY_SERVICE_URI
            - name: TRANSFORM_SERVICE_URI
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: TRANSFORM_SERVICE_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: JWT_SECRET