apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: seongjaegreen/gateway
    newTag: "0000"