apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: seongjaegreen/templify-gateway
  newTag: "202503082343"
