apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: auth
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
images:
- name: seongjaegreen/templify-auth
  newTag: "202503082327"
