apiVersion: apps/v1
kind: Deployment
metadata:
  name: write-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: write
  template:
    metadata:
      labels:
        app: write
    spec:
      containers:
        - name: write
          image: seongjaegreen/templify-write
          ports:
            - containerPort: 8082
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: write-secret
                  key: POSTGRES_URL
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: write-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: write-secret
                  key: POSTGRES_PASSWORD
            - name: TRANSFORM_URL
              valueFrom:
                secretKeyRef:
                  name: write-secret
                  key: TRANSFORM_URL
          lifecycle:
            preStop:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "psql -h $PGHOST -U $PGUSER -d $PGDATABASE -c \"SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE state = 'idle' AND client_addr = '$(hostname -i)';\""