apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: write
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
images:
- name: seongjaegreen/templify-write
  newTag: "202503090005"
