apiVersion: apps/v1
kind: Deployment
metadata:
  name: transform-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transform
  template:
    metadata:
      labels:
        app: transform
    spec:
      containers:
        - name: transform
          image: seongjaegreen/templify-transform
          ports:
            - containerPort: 8083
          env:
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: transform-secret
                  key: POSTGRES_URL
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: transform-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: transform-secret
                  key: POSTGRES_PASSWORD
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: transform-secret
                  key: OPENAI_API_KEY
            - name: HISTORY_URL
              valueFrom:
                secretKeyRef:
                  name: transform-secret
                  key: HISTORY_URL
          lifecycle:
            preStop:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "psql -h $PGHOST -U $PGUSER -d $PGDATABASE -c \"SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE state = 'idle' AND client_addr = '$(hostname -i)';\""