apiVersion: v1
kind: Service
metadata:
  name: transform-service
  namespace: transform
spec:
  selector:
    app: transform
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP